name: 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: DHRUVxMISHRA
          MAX_REPOS: 100
          SETTING_JSON: |
            {
              "type": "calendar",
              "backgroundColor": "#0d1117",
              "textColor": "#58a6ff"
            }

      - uses: actions/upload-artifact@v3
        with:
          name: profile-3d
          path: profile-3d-contrib
