name: 3D Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch
          git switch --orphan output || git switch output
          git rm -rf .
          cp -r profile-3d-contrib/* .
          git add .
          git commit -m "Update 3D contribution graph"
          git push -f origin output
